# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PersonalScheduler' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'KakaoSDKCommon'  # 필수 요소를 담은 공통 모듈
  pod 'KakaoSDKAuth'  # 카카오 로그인
  pod 'KakaoSDKUser'

  pod 'FirebaseCore'
  pod 'FirebaseFirestore'
  pod 'FirebaseAuth'

  # Pods for PersonalScheduler
end
